arch: UNet
batch_size: 16
best_model_val: sdr
dataset: 1381label_lilkely_num15_224_filt5
early_stopping: -1
epochs: 1000
factor: 0.1
gamma: 0.6666666666666666
img_ext: .jpg
img_path: D:\SHS_AI/nested_U/
input_channels: 3
input_h: 224
input_w: 224
loss: MseLoss
lr: 0.0001
mask_ext: .jpg
milestones: 1,2
min_lr: 1.0e-06
momentum: 0.9
name: 1381label_lilkely_num15_224_filt5_UNet_MseLoss_Adam_CosineAnnealingLR
nesterov: false
num_classes: 15
num_workers: 8
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
val_ratio: 0.3
weight_decay: 0.0001
