all_label: JSN_Erosion_finger_full_score_26840.csv
arch: Effnet_Erosion_CE
batch_size: 8
check_path: data_set/
dataset: finger
epochs: 10
factor: 0.1
fold_num: 9
img_ext: .png
inclusion_ratio: 1.0
input_channels: 3
input_h: 144
input_w: 144
loss1: CEL
loss2: kl_divergence
lr: 0.005
min_lr: 1.0e-06
momentum: 0.9
mutual: 'yes'
name: finger_erosion_Full
nesterov: false
num_tasks: 1
num_workers: 1
optimizer1: Adabound
optimizer2: Adabound
over_samp_param: 0.0
patience: 3
restart_fold_num: 0
scheduler: CosineAnnealingLR
task_type: erosion
test_ratio: 0.1
weight_decay: 0.0001
